@Library('shared-library') _  // Load shared library by name (must match Jenkins config)

pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS_ID = 'docker-cred'
        IMAGE_NAME = 'harishkoppineni/my-sample-app'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/arjunkoppineni/my-sample-app.git'
            }
        }

        stage('Build Application') {
            steps {
                script {
                    commonSteps.installAndTestApp('myapp/backend')  // ← shared lib usage
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('myapp/backend') {
                    script {
                        dockerImage = docker.build("${IMAGE_NAME}:latest")
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    commonSteps.deployToK8s('myapp/kubernetes')  // ← shared lib usage
                }
            }
        }
    }
}
